# Generated by Django 4.1.7 on 2023-02-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('create', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
